#!/bin/sh -f

psql -c 'select status_time,gpsnow() - status_time as "Seconds Ago"  from ec_seq order by status_time desc limit 1' | head -3
psql -c 'select node[1]as " Rx ",sig[1] as "Fiber",checksum_err[1],0 as "Delta"  from ec_seq order by status_time desc limit 1' | head -3
psql -c 'select node[2],sig[2]as "Fiber",checksum_err[2],arrival_time[2]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1' | head -3 | tail -1
psql -c 'select node[3],sig[3]as "Fiber",checksum_err[3],arrival_time[3]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[4],sig[4]as "Fiber",checksum_err[4],arrival_time[4]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[5],sig[5]as "Fiber",checksum_err[5],arrival_time[5]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[6],sig[6]as "Fiber",checksum_err[6],arrival_time[6]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1

psql -c 'select node[10],sig[10]as "Fiber",checksum_err[10],arrival_time[10]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[11],sig[11]as "Fiber",checksum_err[11],arrival_time[11]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[12],sig[12]as "Fiber",checksum_err[12],arrival_time[12]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[13],sig[13]as "Fiber",checksum_err[13],arrival_time[13]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[8],sig[8]as "Fiber",checksum_err[8],arrival_time[8]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1
psql -c 'select node[9],sig[9]as "Fiber",checksum_err[9],arrival_time[9]-arrival_time[1] as delta from ec_seq order by status_time desc limit 1'| head -3 | tail -1

